services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"