server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: content
              uri: lb://content-service
              predicates:
                  - Path=/content/**
              filters:
                  - StripPrefix=1
                  - name: RequestRateLimiter
                    args:
                      key-resolver: "#{@ipKeyResolver}"  # resolver lấy IP khách làm key
                      redis-rate-limiter.replenishRate: 5  # thêm 5 token/giây
                      redis-rate-limiter.burstCapacity: 10 # tối đa 10 token
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: routes,health,metrics,routes