server:
  port: 8081

spring:
  application:
    name: content-service

#logging:
#  level:
#    root: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.netflix.eureka: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info