server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nth-joda/pk-reader-config-repo
          default-label: main
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,env